name: Cbeci API production server deploy
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    environment:
      name: TEST_ENV
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: CLI commands for deploy
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        username: cbeci
        port: 22
        envs: SHA
        script_stop: true
        key:  ${{ secrets.CBECI_USER_KEY }}
        script: |
          touch /var/www/html/hello.txt
          echo "Hello world" > /var/www/html/hello.txt
